# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build-node-v8:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v8-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v8-dependencies-

      - run: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v8-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: yarn ci

workflows:
  version: 2
  node-multi-build:
    jobs:
      - build-node-v8
